"""Initial Schema Consolidation

Revision ID: 1b3175d516a0
Revises: 
Create Date: 2026-04-05 17:01:56.321402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '1b3175d516a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('doc_hash', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('colbert_vecs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sparse_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('media_path', sa.String(), nullable=True),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('embedding_valid', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_doc_hash'), 'documents', ['doc_hash'], unique=True)
    op.create_table('eval_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('faithfulness', sa.Float(), nullable=False),
    sa.Column('answer_relevance', sa.Float(), nullable=False),
    sa.Column('context_recall', sa.Float(), nullable=False),
    sa.Column('overall', sa.Float(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eval_results_evaluated_at'), 'eval_results', ['evaluated_at'], unique=False)
    op.create_table('indexed_files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_hash', sa.String(), nullable=False),
    sa.Column('embed_model', sa.String(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indexed_files_filename'), 'indexed_files', ['filename'], unique=True)
    op.create_table('synthetic_qa',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_synthetic_qa_chunk_id'), 'synthetic_qa', ['chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_synthetic_qa_chunk_id'), table_name='synthetic_qa')
    op.drop_table('synthetic_qa')
    op.drop_index(op.f('ix_indexed_files_filename'), table_name='indexed_files')
    op.drop_table('indexed_files')
    op.drop_index(op.f('ix_eval_results_evaluated_at'), table_name='eval_results')
    op.drop_table('eval_results')
    op.drop_index(op.f('ix_documents_doc_hash'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
